#!/bin/bash

if [ $# -lt 2 ] 
then
	echo "Usage: tsvtoxml tsv_input_file xml_output [language-code]"
	echo " tsv_input_file: (required) should be a tab separated values file"
	echo " xml_output: (required) file should be something like strings.xml"
	echo " language_code: (optional) if present, the output file is moved to that values folder, "
	echo "			eg. if language_code is mr, the output file will be moved to res/values-mr folder"
	exit 1
fi

echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>" >$2
echo "<resources>" >>$2

cat $1| while read p || [ -n "$p" ]; do
	value=`echo "$p"| awk -F"\t" '{print ""$2""}' | grep '%.*%'`
	if [ "$value" ] 
	then
		res=`echo "$p"| awk -F"\t" '{print "<string name=\""$1"\" formatted=\"false\">"$2"</string>"}' |sed 's/\r//g'`
	else
		res=`echo "$p"| awk -F"\t" '{print "<string name=\""$1"\">"$2"</string>"}' |sed 's/\r//g'`
	fi
	echo $res >>$2 
	echo $res | grep --color '%'
done 

echo "</resources>" >>$2

# replace $RESPATH with the path of the res folder in your project
#
# make sure the values-xx folders have been created, where xx is the two letter langugae code for the particular language

if [ $# -eq 3 ] 
then
	mv $2 $RESPATH/values-$3/
fi


